# Generated by Django 5.2.4 on 2025-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharthak', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_img',
            field=models.ImageField(upload_to='static/assets/profile/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='picture',
            field=models.ImageField(upload_to='static/assets/picture/'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='static/assets/portfolio/'),
        ),
    ]
