# Generated by Django 5.2.4 on 2025-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharthak', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
